apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-temp
  namespace: sih-solvers-compass
  labels:
    app: chromadb-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb-temp
  template:
    metadata:
      labels:
        app: chromadb-temp
    spec:
      containers:
      - name: chromadb
        image: ghcr.io/chroma-core/chroma:0.4.15
        ports:
        - containerPort: 8000
        env:
        - name: IS_PERSISTENT
          value: "FALSE"  # Temporary - no persistence
        - name: ANONYMIZED_TELEMETRY
          value: "FALSE"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-temp-service
  namespace: sih-solvers-compass
  labels:
    app: chromadb-temp
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: chromadb-temp
