apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: sih-solvers-compass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Further reduced
  storageClassName: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: sih-solvers-compass
  labels:
    app: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: ghcr.io/chroma-core/chroma:0.4.15
        ports:
        - containerPort: 8000
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        - name: PERSIST_DIRECTORY
          value: "/chroma/chroma"
        - name: ANONYMIZED_TELEMETRY
          value: "FALSE"
        resources:
          requests:
            memory: "256Mi"  # Further reduced
            cpu: "125m"      # Further reduced
          limits:
            memory: "512Mi"  # Further reduced  
            cpu: "250m"      # Further reduced
        volumeMounts:
        - name: chromadb-storage
          mountPath: /chroma/chroma
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 60  # Longer delay
          periodSeconds: 15
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: chromadb-storage
        persistentVolumeClaim:
          claimName: chromadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: sih-solvers-compass
  labels:
    app: chromadb
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: chromadb
