apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sih-solvers-compass
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/anurag-bit/sih-tj-frontend:latest  # GHCR instead of ECR
        ports:
        - containerPort: 8080  # Non-privileged port
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Run nginx with mounted config
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        command: ["/bin/sh"]
        args: ["-c", "nginx -g 'daemon off;' "]
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sih-solvers-compass
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  # Map external 80 to internal 8080
  selector:
    app: frontend
